name: Build and deploy Python app to Azure Web App - MyRetailApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run Tests (Optional)
      # Uncomment and add test commands here if you have any test suite
      # - name: Run tests
      #   run: pytest

      # Step 5: Zip the application for deployment
      - name: Zip application for deployment
        run: |
          zip -r release.zip . -x "venv/*" "*.git*" "*.github/*" "__pycache__/*"

      # Step 6: Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting JWT

    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Step 3: Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 4: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          app-name: 'MyRetailApp'
